image:
  repository: ghcr.io/mlflow/mlflow
  tag: latest

postgres:
  host: patroni.default.svc.cluster.local
  port: 5432
  user: mlflow_user
  password: mlflow_pass
  db: mlflow_db

persistence:
  existingClaim: mlflow-pvc
  mountPath: /mlflow/artifacts

ingress:
  enabled: true
  host: mlflow.local
