apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kafka
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      nodePort: {{ .Values.service.nodePort }}
