apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
          volumeMounts:
            - name: kafka-storage
              mountPath: /kafka
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
