apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: NodePort
  selector:
    app: spark
    role: master
  ports:
    - port: {{ .Values.master.port }}
      nodePort: 30077
    - port: {{ .Values.master.uiPort }}
      nodePort: 30080
