apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  type: {{ .Values.worker.service.type | default "ClusterIP" }}
  selector:
    app: spark
    role: worker
  ports:
    - port: {{ .Values.worker.port }}
      targetPort: {{ .Values.worker.port }}
      {{- if eq .Values.worker.service.type "NodePort" }}
      nodePort: {{ .Values.worker.service.nodePort }}
      {{- end }}