apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "{{ .Values.executor }}"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://{{ .Values.postgresql.user }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.db }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.passwordSecret }}
                  key: password
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: "{{ .Values.airflow.secretKey }}"
            - name: AIRFLOW__FERNET_KEY
              value: "{{ .Values.airflow.fernetKey }}"
          ports:
            - containerPort: {{ .Values.airflow.webserverPort }}
          volumeMounts:
            - name: dags
              mountPath: {{ .Values.dags.path }}
            - name: dags
              mountPath: /repo
              subPath: repo

        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.6.2
          volumeMounts:
            - name: dags
              mountPath: /git
          env:
            - name: GIT_SYNC_REPO
              value: "{{ .Values.gitSync.repo }}"
            - name: GIT_SYNC_BRANCH
              value: "{{ .Values.gitSync.branch }}"
            - name: GIT_SYNC_ROOT
              value: "{{ .Values.gitSync.root }}"
            - name: GIT_SYNC_DEST
              value: "{{ .Values.gitSync.dest }}"
            - name: GIT_SYNC_WAIT
              value: "{{ .Values.gitSync.wait }}"
            - name: GIT_SYNC_ONE_TIME
              value: "false"

      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: {{ .Values.dags.persistence.existingClaim }}
