apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
data:
  patroni.yml: |
    bootstrap:
      dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
          use_pg_rewind: true
          parameters:
            wal_level: replica
            hot_standby: "on"
            max_connections: 100
            max_wal_senders: 10
            wal_keep_segments: 8
    postgresql:
      use_unix_socket: true
    restapi:
      listen: 0.0.0.0:8008
      connect_address: 0.0.0.0:8008
    tags:
      nofailover: false
      noloadbalance: false
      clonefrom: false
