apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-init-sql
data:
  init.sql: |
    CREATE USER mlflow_user WITH PASSWORD 'mlflow_pass';
    CREATE DATABASE mlflow_db OWNER mlflow_user;

    CREATE USER airflow WITH PASSWORD 'airflow';
    CREATE DATABASE airflow OWNER airflow;
