apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_SUPERUSER_PASSWORD: c3VwZXJfc2VjcmV0  # base64(super_secret)
  POSTGRES_REPLICATION_PASSWORD: cmVwbGljYXRlX3Bhc3M=  # base64(replicate_pass)
  POSTGRES_ADMIN_PASSWORD: YWRtaW5fcGFzcw==  # base64(admin_pass)