apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/d/codes/interview/csv_files/data/mlflow  # <<< Spesifik lokasyon burası