apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/d/codes/interview/csv_files/data/spark
